Profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, submit_profile

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^edit_profile', edit_profile, name = 'edit_profile'),
    url(r'^submit_profile', submit_profile, name = 'submit_profile'),
    ]

tugas_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import Profile.urls as profile
from django.views.generic.base import RedirectView
import dashboard.urls as dashboard
import update_status.urls as update_status
#import add_friends.urls as add_friends
import add_friends.urls as add_friends

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace = 'profile')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = 'true'), name='index'),
    url(r'^dashboard/', include(dashboard, namespace = 'dashboard')),
    url(r'^friend/', include(add_friends, namespace = 'friend')),
    url(r'^update-status/', include(update_status, namespace = 'update-status')),

]

Profile/models.py
from django.db import models

# Create your models here.

class Account(models.Model):
    name = models.CharField(max_length = 30)
    birth = models.CharField(max_length = 20)
    gender = models.CharField(max_length = 12)
    Expertise = models.TextField()
    Description = models.TextField()
    Email = models.EmailField(default = 'bintangilham41@gmail.com')
    UrlImage = models.TextField()
# Keperluan form edit profile

Profile/forms.py
from django import forms

class EditForm(forms.Form):
    error_message ={
            'required' : 'Isi dengan data valid'
    }
    name_attrs = {
            'type' : 'text',
            'class' : 'profile-input',
            'placeholder': 'Masukan nama ....'
    }
    birth_attrs = {
            'type':'text',
            'class': 'profile-input',
            'placeholder': 'Format: tanggal bulan'
    }
    gender_attrs = {
            'type':'text',
            'class': 'profile-input',
            'placeholder': 'Masukan jatidiri anda'
    }
    Expertise_attrs = {
            'type':'text',
            'class': 'profile-input',
            'placeholder': 'Contoh: Leadership, Negosiator, dll'
    }
    Description_attrs = {
            'type':'text',
            'cols': 50,
            'rows': 4,
            'class': 'profile-input-textarea',
            'placeholder': 'Kamu seperti apa?'
    }
    Email_attrs = {
            'type':'text',
            'class': 'profile-input',
            'placeholder': 'xxxx@xx.com'
    }
    ImageUrl_attrs = {
            'type':'text',
            'cols': 50,
            'rows': 1,
            'class': 'profile-input-textarea',
            'placeholder': 'Url foto kamu'
    }
        
    name = forms.CharField(label  ='',max_length = 50, required =True, widget = forms.TextInput(attrs =name_attrs))
    birth = forms.CharField(label  ='',max_length = 20, required = True, widget = forms.TextInput(attrs =birth_attrs))
    gender = forms.CharField(label  ='',max_length = 12, required = True, widget = forms.TextInput(attrs = gender_attrs))
    Expertise = forms.CharField(label  ='',max_length = 100, widget = forms.TextInput(attrs =Expertise_attrs),required = True)
    Description = forms.CharField(label  ='',max_length = 250,required = True, widget=forms.Textarea(attrs=Description_attrs))
    Email = forms.EmailField(label  ='',required = True, widget = forms.TextInput(attrs = Email_attrs))
    UrlImage = forms.CharField(label  ='',required = True, widget=forms.Textarea(attrs=ImageUrl_attrs))

Profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from .models import Account
from .forms import EditForm


# Create your views here.
response = {}
def index(request):
    html = 'profile_display.html'
    Account.objects.create(name = 'Yumna Pratista Tastaftian', birth = '3 August', gender = 'Male', Expertise = 'Memancing, Berkuda, Basket',
                           Description = 'Aku botak. Aku cinta padamu sampai kaki.', Email = 'yumnanaruto@gmail.com', UrlImage = 'https://i.imgur.com/TWjqJsc.jpg')
    profile = Account.objects.first()
    response['name'] = profile.name
    response['birth'] = profile.birth
    response['gender'] = profile.gender
    response['Expertise'] = profile.Expertise
    response['Description'] = profile.Description
    response['Email'] = profile.Email
    response['UrlImage'] = profile.UrlImage
    response['message'] = ''
    Account.objects.filter(name = 'Yumna Pratista Tastaftian').delete()
    if ('new_profile' in request.GET.dict().keys()):
        if (request.GET.dict()['new_profile'] == 'true'):
            response['message'] = 'Berhasil mengubah profile'
    return render(request, html, response)

def edit_profile(request):
    response['edit_profile'] = EditForm
    html = 'edit_profile.html'
    return render(request, html, response)

def submit_profile(request):
    form = EditForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['birth'] = request.POST['birth']
        response['gender'] = request.POST['gender']
        response['Expertise'] = request.POST['Expertise']
        response['Description'] = request.POST['Description']
        response['Email'] = request.POST['Email']
        response['UrlImage'] = request.POST['UrlImage']
        Account.objects.all().delete()
        profile = Account(name = response['name'], birth = response['birth'], gender = response['gender'], Expertise = response['Expertise'],
                          Description = response['Description'], Email = response['Email'], UrlImage = response['UrlImage'])

        profile.save()
        return HttpResponseRedirect('/profile/?new_profile=true')
    else:
        return HttpResponseRedirect('/edit_profile/')

Profile/templates/edit_profile.html
{% extends "layout/base.html" %}
<!-- css build as internal  type. Please make a base.html soon-->
{% block content %}
        <section name="input-list" id="input-list">
            <div class="container">
                <form id="form" method="POST" action="{% url 'profile:submit_profile' %}">
                    {% csrf_token %}
                    <h3> Name </h3>
                    <p>{{ edit_profile.name }}</p>
                    <h3> Birth </h3>
                    <p>{{ edit_profile.birth}}</p>
                    <h3> Gender </h3>
                    <p>{{ edit_profile.gender}}</p>
                    <h3> Expertise </h3>
                    <p> {{edit_profile.Expertise}}</p>
                    <h3 class="desc"> Description</h3>
                    <p class="desc1"> {{edit_profile.Description}}</p>
                    <h3 class="mail"> Email</h3>
                    <p class="mail1"> {{edit_profile.Email}}</p>
                    <h3 class="url"> Url Foto </h3>
                    <p class="url1"> {{edit_profile.UrlImage}}</p>
                    <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                    <br>
                </form>
            </div>
        </section>
  </body>
{% endblock %}

Profile/templates/profile_display.html
{% extends "layout/base.html" %}
<!-- css build as internal  type. Please make a base.html soon-->
{% block content %}
<section name  = "lookUp" id = "lookUp">
  <div class = "container">
    <h3 class="Profile">Profile</h3>
    <div class="alert alert-success" role="alert-success" id = "message">
      <strong>{{message}}</strong>
    </div>
      <div class = "Image-Profile">
        <img class = "gambar" src= "{{UrlImage}}" alt = "Kuda Yumna" style="height: 150px;
          width: 150px;
          border-radius: 100%;">
        </div>
        <h3 class = "Name_Profile">{{name}}</h3>
      </div>
    </section>
    <section name = "describe" id = "describe">
        <div class="container">
          <div class = "Bio-Profile">
            <h4 class="Birthday1">Birthday</h4>
            <h4 class="Gender1">Gender</h4>
            <h4 class="Expertise1">Expertise</h4>
            <h4 class="Description1">Description</h4>
            <h4 class="Email1">Email</h4>
            <h4 class="Birthday">{{birth}}</h4>
            <h4 class="Gender">{{gender}}</h4>
            <h4 class="Expertise">{{Expertise}}</h4>
            <h4 class="Description">{{Description}}</h4>
            <h4 class="Email">{{Email}}</h4>
          </div>
            <form id = "edit" action="edit_profile">
        <input class="button" type="submit" value="Edit" />
    </form>
  </div>
</section>
  </body>
{% endblock %}