Profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, submit_profile

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^edit_profile', edit_profile, name = 'edit_profile'),
    url(r'^submit_profile', submit_profile, name = 'submit_profile'),
    ]

add_friends/urls.py
from django.conf.urls import url
from .views import index, add_friends_post

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friends_post/$', add_friends_post, name='add_friends_post'),
    ]

tugas_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import Profile.urls as profile
from django.views.generic.base import RedirectView
import dashboard.urls as dashboard
import update_status.urls as update_status
#import add_friends.urls as add_friends
import add_friends.urls as add_friends

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace = 'profile')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = 'true'), name='index'),
    url(r'^dashboard/', include(dashboard, namespace = 'dashboard')),
    url(r'^friend/', include(add_friends, namespace = 'friend')),
    url(r'^update-status/', include(update_status, namespace = 'update-status')),

]

add_friends/models.py
from django.db import models

class Teman(models.Model) :
	nama_teman = models.CharField(max_length=50)
	url_teman = models.CharField(max_length=50)
	tanggal_teman = models.DateTimeField(auto_now_add=True)
# Create your models here.

add_friends/forms.py
from django import forms
from .models import Teman

class addFriendForms(forms.Form):
        error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
        attrs = {
        'class': 'form-control'
    }
        name = forms.CharField(label='NAME', required=True, max_length=30,widget=forms.TextInput(attrs=attrs))
        url = forms.URLField(label = 'URL',required=True,max_length=40,widget=forms.URLInput(attrs=attrs))

add_friends/views.py
from django.shortcuts import render
from .forms import addFriendForms
from .models import Teman
from django.http import HttpResponseRedirect

# Create your views here.
response = {}
def index(request):
    html = 'add_friends/add_friends.html'
    response['addFriendForms'] = addFriendForms
    teman = Teman.objects.all()
    response['teman'] = teman
    return render(request, html, response)

def add_friends_post(request):
    form = addFriendForms(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        teman = Teman(nama_teman=response['name'], url_teman=response['url'])
        teman.save()
        html ='add_friends/add_friends.html'
        return render(request, html, response)

add_friends/templates/add_friends/add_friends.html
{% extends "dashboard/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
<link href='https://fonts.googleapis.com/css?family=Concert+One' rel='stylesheet' type='text/css'>
{% endblock %}
{% block title %} Friend List {% endblock %}

{% block content %}

<style type="text/css">
    body{
     background: #acb6e5;  /* fallback for old browsers */
background: -webkit-linear-gradient(to top, #86fde8, #acb6e5);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to top, #86fde8, #acb6e5); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

}
.long-shadow {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  padding: 25px;
  border: none;
  font: normal 70px/1 "Fredoka One", Helvetica, sans-serif;
  color: rgba(255,255,255,1);
  text-align: center;
  -o-text-overflow: clip;
  text-overflow: clip;
  text-shadow: 3px 3px 0 #0199d9 , 4px 4px 0 #0199d9 , 5px 5px 0 #0199d9 , 6px 6px 0 #0199d9 , 7px 7px 0 #0199d9 , 8px 8px 0 #0199d9 , 9px 9px 0 #0199d9 , 10px 10px 0 #0199d9 , 11px 11px 0 #0199d9 , 12px 12px 0 #0199d9 , 13px 13px 0 #0199d9 , 14px 14px 0 #0199d9 , 15px 15px 0 #0199d9 , 16px 16px 0 #0199d9 , 17px 17px 0 #0199d9 , 18px 18px 0 #0199d9 , 19px 19px 0 #0199d9 , 20px 20px 0 #0199d9 ;
}
.button {
  display: inline-block;
  border-radius: 4px;
  background-color: #07BEB8;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 20px;
  padding: 5px;
  width: 150px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
  height:40px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}
.button {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}
.card {
    background: rgba(51, 51, 51, 0.1);
    margin-top: 1rem;
    padding: 1rem;
    margin-bottom: 1rem;
 }
#input-friend:hover {
  top: -5px;
  -webkit-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
  -o-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
}

#title-friend {
  padding-top: 10px;
  text-align: left;
}

.Teman .Teman-url {
  font-size: 12px;
  padding: 0 10px;
}
#added-friend {
  font-size: 12px;
  padding-top: 0px;
  padding-bottom: 20px;
}

.flex{
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: flex-start;
  align-items: flex-start;
  align-content: flex-start;
  padding-top: 20px;
  padding-bottom: 15px;
  margin-right: 15px;
  margin-left: 10px;
}

.flex-item{
  padding: 0 15px;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: 25%;
  background: white;
  border-radius: 15px;
  margin: 30px;
}

/* styling responsive max-width menandakan bahwa rule css ini hanya akan bekerja untuk layar dengan maksimal 768px, jika lebih dari 768px maka rule ini diabaikan */
@media only screen and (max-width: 768px) {
  #input-friend form {
      width: 290px;
  }

  .flex {
    bottom: -50px;
  }

  .flex-item{
    padding: 0 15px;
    flex-grow: 0;
    flex-shrink: 0;
    flex-basis: 100%;
  }
}
</style>
<body>
<content>
<section>
    <div class="container">
      <div class="text-center">
      <br>
      <br>
        <div class="long-shadow">MY COOL FRIEND </div>
      </div>
        <div class="row">
            <div class="col-sm-offset-2 col-sm-8 text-center">
                <form id="form" method="POST" action="{% url 'friend:add_friends_post'%}" style="padding-top: 30px; font-family: Concert One; font-size: 20px; color: #">
                {% csrf_token%}
                {{addFriendForms}}
                <br>
                <button type="submit" style="vertical-align:middle;" id="button" class="button"><span>ADD</span></button>
                </form>
            </div>
        </div>
    </div>
</section>

<section>
<br>
<br>
    <div class="container">
    <div class="flex">
    {% if teman %}
        {% for x in teman %}
        
        <div class="flex-item text-center">
            <div class="list-friend">
            <br>
            <div  align="center"><img alt="User Pic" src="https://ibb.co/kKUhkb" width="150" height="150" class="img-circle img-responsive" style="text-align: center"></div>
            <h4 id="title-friend" style="text-align: center; color: black">{{x.nama_teman}}</h4>
                <div id="added-friend" style="color: black">Added on {{x.tanggal_teman}}</div>
                <a href="{{x.url_teman}}" target="_blank">{{x.url_teman}}</a>
                <br>
                <br>
            </div>
        </div>
        {% endfor %}
    {% endif %}
    </div>
    </div>
</section>

</body>
</html>
</content>
{% endblock %}