Profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, submit_profile

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^edit_profile', edit_profile, name = 'edit_profile'),
    url(r'^submit_profile', submit_profile, name = 'submit_profile'),
    ]

tugas_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import Profile.urls as profile
from django.views.generic.base import RedirectView
import dashboard.urls as dashboard
import update_status.urls as update_status
#import add_friends.urls as add_friends
import add_friends.urls as add_friends

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace = 'profile')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = 'true'), name='index'),
    url(r'^dashboard/', include(dashboard, namespace = 'dashboard')),
    url(r'^friend/', include(add_friends, namespace = 'friend')),
    url(r'^update-status/', include(update_status, namespace = 'update-status')),

]

update_status/urls.py
from django.conf.urls import url
from .views import index, message_post

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
 ]

update_status/models.py
from django.db import models

class Message(models.Model):
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

update_status/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

response = {}
def index(request):
    html = 'update_status/update_status.html'
    response['message_form'] = Message_Form
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if((request.method == 'POST') and form.is_valid()):
        response['message'] = request.POST['message']
        message = Message(message=response['message'])
        message.save()
        message = Message.objects.all()
        response['message'] = message
        return render(request, 'update_status/update_status.html', response)
    else:        
        return HttpResponseRedirect('/update-status/')

update_status/templates/update_status/update_status.html
{% extends "dashboard/layout/base.html" %}

{% block title %} Status {% endblock %}

{% block content %}

<hr/>
<section name="form">
    <h2>Update Status kamu</h2>
    <form id="form" method="POST" action="{% url 'update-status:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Post</button>
    </form>
</section>
<hr/>

<div class="latest-post">
    <h4>Timeline</h4>
    <hr style="border-color: black;width: 100%;">
	<br>
	{% for i in message reversed %}
	<div class="col-lg-8 post">
		<div class="col-lg-2">
            <img class = "profile_pict_kecil" src="https://cdn.pixabay.com/photo/2013/09/01/14/06/horse-178093_960_720.jpg">
            <h4>{{i.message}}</h4> 
		</div>
		<div class="col-lg-6">
            <h3>Yumna Pratista Tastaftian</h3>
            <h6>{{i.created_date.date}} {{i.created_date.time}}</h6>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}